"""adds column unit to inventory

Revision ID: 32ced0e99842
Revises: cee99d537b13
Create Date: 2023-08-27 22:14:33.171887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32ced0e99842'
down_revision: Union[str, None] = 'cee99d537b13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.String(), nullable=True))
        batch_op.create_unique_constraint("add_unit", ['unit'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_constraint("add_unit", type_='unique')
        batch_op.drop_column('unit')

    # ### end Alembic commands ###
