"""updated second table Columns

Revision ID: a3a2f6991b3c
Revises: b86544e2106f
Create Date: 2023-08-23 19:40:15.909522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3a2f6991b3c'
down_revision: Union[str, None] = 'b86544e2106f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nail_polishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('polishType', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('salon_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['salon_id'], ['inventory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('nail_types')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nail_types',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('white_tip', sa.BOOLEAN(), nullable=True),
    sa.Column('shape', sa.VARCHAR(), nullable=True),
    sa.Column('size', sa.INTEGER(), nullable=True),
    sa.Column('salon_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['salon_id'], ['inventory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('nail_polishes')
    # ### end Alembic commands ###
