"""added second table Columns

Revision ID: b86544e2106f
Revises: 703c2143f1e5
Create Date: 2023-08-23 19:20:02.322096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b86544e2106f'
down_revision: Union[str, None] = '703c2143f1e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nail_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('white_tip', sa.Boolean(), nullable=True),
    sa.Column('shape', sa.String(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('salon_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['salon_id'], ['inventory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nail_types')
    # ### end Alembic commands ###
