"""create column in place order table

Revision ID: bd161d28cba7
Revises: c9a213e69182
Create Date: 2023-08-27 21:15:02.854293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd161d28cba7'
down_revision: Union[str, None] = 'c9a213e69182'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('place_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_number', sa.String(), nullable=True))
        batch_op.create_unique_constraint("order_salon", ['order_number'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('place_order', schema=None) as batch_op:
        batch_op.drop_constraint("order_salon", type_='unique')
        batch_op.drop_column('order_number')

    # ### end Alembic commands ###
