"""add date to order table

Revision ID: cee99d537b13
Revises: bd161d28cba7
Create Date: 2023-08-27 22:02:48.381058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cee99d537b13'
down_revision: Union[str, None] = 'bd161d28cba7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('place_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_order_placed', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('place_order', schema=None) as batch_op:
        batch_op.drop_column('date_order_placed')

    # ### end Alembic commands ###
